GRPO_PROMPT = (
    "{Question} "
    "First, output the thinking process in <think>...</think> tags, "
    "producing a concise and precise analysis by only describing the most decisive AUs and how these lead to your emotion inference. "
    "Seamlessly integrate only truly relevant AU numbers (in parentheses), directly tying each to your emotional reasoning—avoid uncertainty, negations, or mentioning unlikely emotions. "
    "Use these AU definitions and their possible emotional associations:"
    "\\nAU1: Inner brow raiser [Sadness, Fear, Surprise]; "
    "AU2: Outer brow raiser [Fear, Surprise]; "
    "AU4: Brow lowerer [Anger, Sadness]; "
    "AU5: Upper lid raiser [Fear, Surprise]; "
    "AU6: Cheek raiser [Happiness]; "
    "AU7: Lid tightener [Anger, Sadness]; "
    "AU9: Nose wrinkler [Disgust]; "
    "AU10: Upper lip raiser [Disgust]; "
    "AU11: Nasolabial Furrow Deepener; "
    "AU12: Lip corner puller [Happiness]; "
    "AU13: Cheek puffer; "
    "AU14: Dimpler; "
    "AU15: Lip corner depressor [Sadness]; "
    "AU16: Lower lip depressor [Sadness, Disgust]; "
    "AU17: Chin raiser [Disgust, Anger]; "
    "AU18: Lip pucker [Sadness, Anger]; "
    "AU19: Tongue show; "
    "AU20: Lip stretcher [Fear]; "
    "AU22: Lip funneler; "
    "AU23: Lip tightener [Anger]; "
    "AU24: Lip pressor [Anger]; "
    "AU25: Lips parted [Surprise, Fear]; "
    "AU26: Jaw drop [Surprise]; "
    "AU27: Mouth stretch [Surprise, Fear]; "
    "AU28: Lip suck; "
    "AU29: Jaw thrust; "
    "AU30: Jaw sideways; "
    "AU31: Jaw clencher [Anger]; "
    "AU32: Lip bite [Sadness, Fear]; "
    "AU43: Eyes closed.\\n"
    "After the thinking process, output only the final emotion—choose one from [anger, happiness, sadness, neutral, disgust, surprise, fear]—as a single word in <answer>...</answer> tags.\\n"
    "Here is a sample of the required analysis style:"
    "\\n<think>The man's eyebrows are pulled together and lowered (AU4), and the mouth corners are downturned (AU15). This combination of brow lowering (AU4) and mouth corner depression (AU15) is a strong indicator of sadness.</think> "
    "<answer>sadness</answer>"
)

# GRPO_PROMPT = (  
#     "{Question} "  
#     "First output the thinking process in <think>...</think> tags, "  
#     "then output the final emotion—choose only from [anger, happiness, sadness, neutral, disgust, surprise, fear]—using one word in <answer>...</answer> tags."  
# )

SFT_PROMPT = (  
    "{Question} "  
    "Output the final emotion—choose only from [anger, happiness, sadness, neutral, disgust, surprise, fear]."  
)